config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  resources :prototypes do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]
  scope module: :prototypes do
    resources :popular, only: :index
  end
  resources :tags, only: [:index, :show]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :prototype, counter_cache: :likes_count
  belongs_to :user
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many :prototype_images
  has_many :likes, dependent: :destroy
  has_many :comments
  accepts_nested_attributes_for :prototype_images, allow_destroy: true, reject_if: proc { |attributes| attributes['content'].blank? }
  validates :title, :catchcopy, :concept, :prototype_images, presence: true
  paginates_per 8
  acts_as_taggable
  acts_as_taggable_on :prototypes

  def user_liked?(user)
    likes.find_by(user_id: user)
  end
end

app/models/prototype_image.rb
class PrototypeImage < ActiveRecord::Base
  enum role: %i(main sub)
  belongs_to :prototype
  mount_uploader :content, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :image, ImageUploader
  has_many :prototypes
  has_many :likes
  has_many :comments
  validates :email, :username, :member, :profile, :work, :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :member, :profile, :work, :image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_prototype
  def create
    Comment.create(comment_params)
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, prototype_id: @prototype.id)
  end

  def set_prototype
    @prototype = Prototype.find(params[:prototype_id])
    @comments = @prototype.comments
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, prototype_id: params[:prototype_id])
    set_variables
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, prototype_id: params[:prototype_id])
    like.destroy
    set_variables
  end

  def set_variables
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
  end
end

app/controllers/prototypes/popular_controller.rb
class Prototypes::PopularController < ApplicationController
  def index
    @prototypes = Prototype.includes(:prototype_images).order(likes_count: :desc).page(params[:page])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :set_prototype, only: %i(update destroy show edit)
  def index
    @prototypes = Prototype.includes(:prototype_images).order(created_at: :desc).page(params[:page])
  end

  def new
    @prototype = Prototype.new
    @prototype.prototype_images.build
  end

  def show
    @like = Like.find_by(prototype_id: @prototype.id)
    @comments = @prototype.comments
    @tags = @prototype.tags
    @comment = Comment.new(prototype_id: @prototype.id, user_id: current_user.id) if current_user
  end

  def create
    @prototype = Prototype.new(prototype_params)
    if @prototype.save
      flash[:notice] = "Create Success"
      redirect_to action: :index
    else
      flash[:alert] = "Could Not Create"
      render action: :new
    end
  end

  def edit
    @prototype.prototype_images.build
  end

  def destroy
    @prototype = Prototype.find(params[:id])
    if @prototype.user.id == current_user.id
      @prototype.destroy
    end
    redirect_to action: :index
    flash[:notice] = "Successfully Deleted"
  end

  def update
    @prototype = Prototype.find(params[:id])
    if @prototype.user.id == current_user.id
      @prototype.update(prototype_params)
    end
    redirect_to action: :index
    flash[:notice] = "Successfully Edited"
  end

  private
  def set_prototype
      @prototype = Prototype.find(params[:id])
  end

  def prototype_params
    params.require(:prototype).permit(
    :id,
    :title,
    :text,
    :catchcopy,
    :concept,
    prototype_images_attributes: [:id, :content, :role])
    .merge(
    user_id: current_user.id,
    tag_list: params[:prototype][:tag])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.most_used
  end

  def show
    @tag = params[:id]
    @prototypes = Prototype.tagged_with(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @prototypes = @user.prototypes.order(created_at: :desc).page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.id == current_user.id
      user.update(user_params)
    end
    redirect_to action: :show
  end

  def user_params
    params.permit(:email, :password, :username, :member, :profile, :work, :image).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.haml
%h4.col-md-12
  Comments
  %span.num ( #{ comments.length } )
.col-md-8
  - comments.each do |comment|
    .media
      .media-left
        = link_to image_tag(comment.user.image, style: 'width: 64px; height: 64px;'), user_path(comment.user)
      .media-body
        %h4#top-aligned-media.media-heading
          = comment.user.username
          = link_to 'DELETE', prototype_comment_path(comment, prototype_id: @prototype.id), method: :delete, remote: true, class: "btn btn-primary btn-xs"
        %p= comment.text

app/views/comments/create.js.haml
$('#comment_field').val('');
$('#comments').html(
'#{j(render partial: 'comments/comment', locals: {comments: @comments})}'
);

app/views/comments/destroy.js.haml
$('#comments').html('#{j(render partial: 'comments/comment', locals: {comments: @comments})}');

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.
  

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      -if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", href: "#", role: "button"}
              = current_user.username
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to "Profile Edit", edit_user_path(current_user)
              %li
                = link_to "Log out", destroy_user_session_path, method: :delete
              %li
                = link_to "My Page", user_path(current_user)
          %li
            .btn.btn-primary.navbar-btn
              = link_to "New Proto", new_prototype_path
      -else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to "Get Started", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" => "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = bootstrap_flash
    = yield
    = render "layouts/footer"

app/views/likes/_like.html.haml
- if user_signed_in?
  - if prototype.like_user(current_user.id)
    = button_to prototype_like_path(like, prototype_id: prototype.id), method: :delete, id: "like-button", remote: true do
      = image_tag("icon_red_heart.svg")
      %span
        = prototype.like_count
  - else
    = button_to prototype_likes_path(tweet), id: "like-button", remote: true do
      = image_tag("icon_heart.svg")
      %span
        = prototype.like_count
- else
  - = image_tag("icon_heart.svg")
  %span
    = prototype.like_count

app/views/likes/create.js.haml
$("#like-buttons").html("#{j(render partial: 'prototypes/like', locals: { prototype: @prototype, likes: @likes, like: @like})}")

app/views/likes/destroy.js.haml
$("#like-buttons").html("#{j(render partial: 'prototypes/like', locals: { prototype: @prototype, likes: @likes })}");

app/views/prototypes/_like.html.haml
- if user_signed_in?
  - if prototype.user_liked?(current_user.id)
    = button_to prototype_like_path(like, prototype_id: prototype), method: :delete, id: 'like-button', remote: true do
      = image_tag('icon_red_heart.svg')
      %span
        = prototype.likes_count
  - else
    = button_to prototype_likes_path(prototype), id: 'like-button', remote: true do
      = image_tag('icon_heart.svg')
      %span
        = prototype.likes_count
- else
  = button_to do
    = image_tag('icon_heart.svg')
    %span
      = prototype.likes_count

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-conent
  .thumbnail
    = link_to image_tag(prototype.prototype_images.main.first.content), prototype_path(prototype)
    .caption
      %h3= prototype.title
      .proto-meta
        .proto-user
          = link_to "by #{ prototype.user.username }", user_path(prototype.user)
        .proto-posted
          = prototype.created_at.strftime("%b %d %Y")
      %ul.proto-tag-list.list-inline
        - prototype.tags.each do |tag|
          %li
            =link_to "#{ tag.name }", tag_path(tag.name)

app/views/prototypes/edit.html.haml
.conrainer.proto-new
  = form_for @prototype do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          .proto-new-title
            = f.text_area :title, placeholder: "Title", class: "proto-new-title"
      .row
        .col-md-12
          .cover-image-upload
            = f.fields_for :prototype_images do |image|
              = image.hidden_field :role, value: :main
              = image.file_field :content
          .col-md-12
            %ul.proto-sub-list.list-group
              - 2.times do
                %li.list-group-item.col-md-4
                  .image-upload
                    = f.fields_for :prototype_images do |image|
                      = image.hidden_field :role, value: :sub
                      = image.file_field :content
              %li.list-group-item.col-md-4
                .image-upload-plus
                  %span +
      .row.proto-description
        .col-md-12
          = f.text_area :catchcopy, placeholder: "Catch Copy"
        .col-md-12
          = f.text_area :concept, cols: "30", rows: "4", placeholder: "Concept"
        .col-md-12
          %h4 Tag List
          .row
            .col-md-3
              = text_field_tag "prototype[tag][]", "", placeholder: "Web Design"
            .col-md-3
              = text_field_tag "prototype[tag][]", "", placeholder: "UI"
            .col-md-3
              = text_field_tag "prototype[tag][]", "", placeholder: "Application"
      .row.text-center.proto-btn
        = f.submit "Publish", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag('header_logo.png', alt: 'PROTO TYPE - SHARE THE PROTOTYPE', height: '73px')

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li{role: 'presentation'}
          = link_to 'Popular PROTO', popular_index_path
        %li.active{role: 'presentation'}
          = link_to 'Newest PROTO', root_path
        %li{ style: 'padding: 0 0 0 690px'}
          = link_to 'View Tags', tags_path, class: 'btn btn-default', method: :get

.container.proto-list
  .row
    = render partial: 'prototype', collection: @prototypes

.text-center
  = paginate(@prototypes)

app/views/prototypes/new.html.haml
.conrainer.proto-new
  = form_for @prototype do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          .proto-new-title
            = f.text_area :title, placeholder: 'Title', class: 'proto-new-title'
      .row
        .col-md-12
          .cover-image-upload
            = f.fields_for :prototype_images do |image|
              = image.hidden_field :role, value: :main
              = image.file_field :content
          .col-md-12
            %ul.proto-sub-list.list-group
              - 2.times do
                %li.list-group-item.col-md-4
                  .image-upload
                    = f.fields_for :prototype_images do |image|
                      = image.hidden_field :role, value: :sub
                      = image.file_field :content
              %li.list-group-item.col-md-4
                .image-upload-plus
                  %span +
      .row.proto-description
        .col-md-12
          = f.text_area :catchcopy, placeholder: 'Catch Copy'
        .col-md-12
          = f.text_area :concept, cols: '30', rows: '4', placeholder: 'Concept'
        .col-md-12
          %h4 Tag List
          .row
            .col-md-3
              = text_field_tag 'prototype[tag][]', '', placeholder: 'Web Design'
            .col-md-3
              = text_field_tag 'prototype[tag][]', '', placeholder: 'UI'
            .col-md-3
              = text_field_tag 'prototype[tag][]', '', placeholder: 'Application'
    .row.text-center.proto-btn
      = f.submit 'Publish', class: 'btn btn-lg btn-primary btn-block'

app/views/prototypes/popular/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{ role: :presentation }
          = link_to "Popular PROTO", popular_index_path
        %li{ role: :presentation }
          = link_to "Newest PROTO", root_path
      %button{ type: "button", class: "btn btn-default col-lg-1" } View Tags

.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes

.text-center
  = paginate(@prototypes)

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(@prototype.user) do
            = image_tag(@prototype.user.image, style: 'width: 64px; height: 64px;')
        .media-body
          %h4#top-aligned-media.media-heading= @prototype.title
          - if user_signed_in?
            = link_to 'EDIT', edit_prototype_path, class: 'btn btn-primary btn-xs'
            = link_to 'DELETE', "/prototypes/#{ @prototype.id }", method: :delete, class: 'btn btn-primary btn-xs'
          .proto-user
            = link_to "by #{ @prototype.user.username }", user_path(@prototype.user)
            %span.degree we-b inc. Designer

    .col-md-6.text-right
      #like-buttons
        = render partial: 'like', locals: {prototype: @prototype, like: @like}
  .row
    .col-md-9
      = image_tag(@prototype.prototype_images.main.first.content, class: 'img-responsive')
    .col-md-3
      %ul.proto-sub-list.list-group
      - @prototype.prototype_images.sub.each do |sub_image|
        %li.list-group-item
          = image_tag(sub_image.content, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catchcopy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @tags.each do |tag|
          %li.btn.btn-default
            =link_to "#{ tag.name }", tag_path(tag.name)

  .row.proto-comments
    #comments
      = render partial: 'comments/comment', locals: {comments: @comments}
    - if current_user
      .form-inline
        = form_for [@prototype, @comment], remote: true do |f|
          %h4.write_comment Write a comment
          .row
            .form-group.col-md-10
              = f.text_area :text, placeholder:  'Your comments', rows: '3', id: 'comment_field'
            .form-group.col-md-2
              = f.submit 'Comment', class: 'btn btn-primar'

app/views/prototypes/update.html.haml
.row.form_for
  .col-lg-12
    %h3 Tweet Successfully Edited
    = link_to "Move to Top", root_path

app/views/tags/index.html.haml
.container
  %h2 Tags List
  %ul
    - @tags.each do |tag|
      %li.btn.btn-default.btn-lg.col-xs-3
        = link_to "#{tag.name}", tag_path(tag.name)

app/views/tags/show.html.haml
.container
  %h2
    = @tag
  .container.proto-list
    .row
      = render partial: 'prototypes/prototype', collection: @prototypes

app/views/users/edit.html.haml
.container.user-new
  = form_for (@user) do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit Profile
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :username, placeholder: "Username"
            .user-image.col-md-2{style: 'background-image: url(http://泣ける動画.com/wp-content/uploads/2015/01/t0205-01.jpg);'}
              %button.btn.btn-primary Change image
              = f.file_field :image
          = f.email_field :email, placeholder: "E-Mail", class: "user-email"
          = f.password_field :password, placeholder: "Password", class: "user-password"
        .col-md-12
          %h4 Member of
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :member, placeholder: "Member"
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, cols: "30", rows: "4", placeholder: "Profile"
          %h4 Works
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :work, cols: "30", rows: "4", placeholder: "Works"
    .row.text-center.user-btn
      = f.submit "Save", class: "btn btn-lg btn-primary btn-block"

app/views/users/index.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        %a{:href => "#"}
          %img.media-object{:alt => "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", :src => "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", :style => "width: 64px; height: 64px;"}/
      .media-body
        %h4#top-aligned-media.media-heading
          Top aligned media
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree we-b inc. Designer
        .row
          .col-md-6
            %h4 Profile
            %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          .col-md-6
            %h4 Works
            %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
.container.proto-list
  .row
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li 
                %a{:href => "#", :class => "btn btn-default"} wireframe
                
.text-center
  %ul.pagination
    %li.disabled
      %a{"aria-label" => "Previous", :href => "#"}
        %span{"aria-hidden" => "true"} «
    %li.active
      %a{:href => "#"}
        1
        %span.sr-only (current)
    %li
      %a{:href => "#"} 2
    %li
      %a{:href => "#"} 3
    %li
      %a{:href => "#"} 4
    %li
      %a{:href => "#"} 5
    %li
      %a{"aria-label" => "Next", :href => "#"}
        %span{"aria-hidden" => "true"} »

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = link_to user_path(@user) do
          = image_tag(@user.image, style: "width: 64px; height: 64px;")
      .media-body
        %h4#top-aligned-media.media-heading
          Top aligned media
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree we-b inc. Designer
        .row
          .col-md-6
            %h4 Profile
            %p
              = @user.profile
          .col-md-6
            %h4 Works
            %p
              = @user.work
.container.proto-list
  .row
    = render partial: "prototypes/prototype", collection: @prototypes

.text-center
  = paginate(@prototypes)